### ISSUE TITLE
How do I generate a clusters.tsv?

### ISSUE THREAD

**Issue by matbeedotcom** [El-Mundo/SimpleFaceClustering#1]
I havent found how you generated a clusters.tsv file. Would be nice to have a sorted list by cluster id

**Comment by El-Mundo** [comment]
You can save the clusters.tsv with key E.

Sorry key E was mistakenly written to export CSVs in readme. Now I have fixed it.

**Comment by matbeedotcom** [comment]
This is excellent, thank you!
